# Generated by Django 4.2.11 on 2024-04-22 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[w.@+-]+Z', message='Недопустимые символы в поле username')], verbose_name='Уникальный юзернейм'),
        ),
    ]
